##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

server_names = ["google", "cloudflare", "cloudflare-2", "cloudflare-3", "cloudflare-4", "cloudflare-5", "cloudflare-6", "cloudflare-7", "cloudflare-8", "odoh-cloudflare", "nextdns", "dns0-unfiltered", "fdn", "sth-dnscrypt-se", "scaleway-fr", "odoh-koki-ams", "dnscry-pt-tallin-ipv4", "odoh-koki-se", "dnscrypt-pl", "odoh-jp-tiar-app"]

listen_addresses = ['127.0.0.1:53']

max_clients = 250

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = true
http3 = false
timeout = 1000
keepalive = 20
blocked_query_response = 'refused'
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true

[blocked_names]
blocked_names_file = 'blocked-names.txt'

[blocked_ips]
blocked_ips_file = 'blocked-ips.txt'

[allowed_names]
allowed_names_file = 'allowed-names.txt'

[allowed_ips]
allowed_ips_file = 'allowed-ips.txt'

[static]
  [static.google]
    stamp = 'sdns://AgUAAAAAAAAABzguOC44LjggsKKKE4EwvtIbNjGjagI2607EdKSVHowYZtyvD9iPrkkHOC44LjguOAovZG5zLXF1ZXJ5'
  [static.cloudflare]
    stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEAEmRucy5jbG91ZGZsYXJlLmNvbQovZG5zLXF1ZXJ5'
  [static.cloudflare-2]
    stamp = 'sdns://AgcAAAAAAAAABzEuMS4xLjEABzEuMS4xLjEKL2Rucy1xdWVyeQ'
  [static.cloudflare-3]
    stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjEABzEuMC4wLjEKL2Rucy1xdWVyeQ'
  [static.cloudflare-4]
    stamp = 'sdns://AgcAAAAAAAAADDE2Mi4xNTkuMzYuMQAMMTYyLjE1OS4zNi4xCi9kbnMtcXVlcnk'
  [static.cloudflare-5]
    stamp = 'sdns://AgcAAAAAAAAADjEwNC4xNi4xMzIuMjI5ABJkbnMuY2xvdWRmbGFyZS5jb20KL2Rucy1xdWVyeQ'
  [static.cloudflare-6]
    stamp = 'sdns://AgcAAAAAAAAADjEwNC4xNi4xMzMuMjI5ABJkbnMuY2xvdWRmbGFyZS5jb20KL2Rucy1xdWVyeQ'
  [static.cloudflare-7]
    stamp = 'sdns://AgcAAAAAAAAADjEwNC4xNi4yNDkuMjQ5ABJjbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ'
  [static.cloudflare-8]
    stamp = 'sdns://AgcAAAAAAAAADjEwNC4xNi4yNDguMjQ5ABJjbG91ZGZsYXJlLWRucy5jb20KL2Rucy1xdWVyeQ'
  [static.nextdns]
    stamp = 'sdns://AgcAAAAAAAAACjQ1LjkwLjMwLjAgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkWYW55Y2FzdC5kbnMubmV4dGRucy5pbwovZG5zLXF1ZXJ5'
  [static.fdn]
    stamp = 'sdns://AgcAAAAAAAAADDgwLjY3LjE2OS40MKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5qD39a8ogB6HfX3zor4o_hSfMnSn7SnxNv1QPOOYy6gLDaCzXgWVDPvYJZ-TdboQGHC4w8TA7FpSl1fmMWfp3iap6KBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zqDmRLppY-M1_nZcuZdrErEOtUKUtCR3dkzLOjrMo6yy_CAqrj-3vwXkyBxBlNykRRHU-a8wR4bsGuchhAnPYqCDVQpuczEuZmRuLmZyCi9kbnMtcXVlcnk'
  [static.sth-dnscrypt-se]
    stamp = 'sdns://AQcAAAAAAAAAEjQ1LjE1My4xODcuOTY6NDM0MyDE1pgPAnfh06z6updfy39KN8PbJQHdDzVU4zEMfbeoQR8yLmRuc2NyeXB0LWNlcnQuc3RoLWRuc2NyeXB0LXNl'
  [static.scaleway-fr]
    stamp = 'sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc'
  [static.dnscrypt-pl]
    stamp = 'sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDUzIH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5wbA'
