##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

server_names = ["google", "cloudflare", "odoh-cloudflare", "nextdns", "dns0-unfiltered", "fdn", "sth-dnscrypt-se", "scaleway-fr", "odoh-koki-ams", "dnscry-pt-tallin-ipv4", "odoh-koki-se", "dnscrypt-pl", "odoh-jp-tiar-app"]

listen_addresses = ['127.0.0.1:5354']

max_clients = 250

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = true
http3 = false
timeout = 1000
keepalive = 20
blocked_query_response = 'refused'
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = true

[blocked_names]
blocked_names_file = 'blocked-names.txt'

[blocked_ips]
blocked_ips_file = 'blocked-ips.txt'

[allowed_names]
allowed_names_file = 'allowed-names.txt'

[allowed_ips]
allowed_ips_file = 'allowed-ips.txt'

[static]
  [static.google]
    stamp = 'sdns://AgUAAAAAAAAABzguOC44LjggsKKKE4EwvtIbNjGjagI2607EdKSVHowYZtyvD9iPrkkHOC44LjguOAovZG5zLXF1ZXJ5'
  [static.cloudflare]
    stamp = 'sdns://AgcAAAAAAAAADDE2Mi4xNTkuNDYuMQAMMTYyLjE1OS40Ni4xCi9kbnMtcXVlcnk'
  [static.odoh-cloudflare]
    stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'
  [static.nextdns]
    stamp = 'sdns://AgcAAAAAAAAACjQ1LjkwLjMwLjAgmjo09yfeubylEAPZzpw5-PJ92cUkKQHCurGkTmNaAhkWYW55Y2FzdC5kbnMubmV4dGRucy5pbwovZG5zLXF1ZXJ5'
  [static.dns0-unfiltered]
    stamp = 'sdns://BQcAAAAAAAAADm9kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk'
  [static.fdn]
    stamp = 'sdns://AgcAAAAAAAAADDgwLjY3LjE2OS40MKDMEGDTnIMptitvvH0NbfkwmGm5gefmOS1c2PpAj02A5qD39a8ogB6HfX3zor4o_hSfMnSn7SnxNv1QPOOYy6gLDaCzXgWVDPvYJZ-TdboQGHC4w8TA7FpSl1fmMWfp3iap6KBETr1nu4P4gHs5Iek4rJF4uIK9UKrbESMfBEz18I33zqDmRLppY-M1_nZcuZdrErEOtUKUtCR3dkzLOjrMo6yy_CAqrj-3vwXkyBxBlNykRRHU-a8wR4bsGuchhAnPYqCDVQpuczEuZmRuLmZyCi9kbnMtcXVlcnk'
  [static.sth-dnscrypt-se]
    stamp = 'sdns://AQcAAAAAAAAAEjQ1LjE1My4xODcuOTY6NDM0MyDE1pgPAnfh06z6updfy39KN8PbJQHdDzVU4zEMfbeoQR8yLmRuc2NyeXB0LWNlcnQuc3RoLWRuc2NyeXB0LXNl'
  [static.scaleway-fr]
    stamp = 'sdns://AQcAAAAAAAAADjIxMi40Ny4yMjguMTM2IOgBuE6mBr-wusDOQ0RbsV66ZLAvo8SqMa4QY2oHkDJNHzIuZG5zY3J5cHQtY2VydC5mci5kbnNjcnlwdC5vcmc'
  [static.odoh-koki-ams]
    stamp = 'sdns://BQcAAAAAAAAAFG9kb2gtbmwuYWxla2JlcmcubmV0Ci9kbnMtcXVlcnk'
  [static.dnscry-pt-tallin-ipv4]
    stamp = 'sdns://AQcAAAAAAAAADTE4NS4xOTQuNTMuMjIgr0WageGep9cjA5yYpY30Z6EsTYHZnSlV-PCfvZssTNcZMi5kbnNjcnlwdC1jZXJ0LmRuc2NyeS5wdA'
  [static.odoh-koki-se]
    stamp = 'sdns://BQcAAAAAAAAAFG9kb2gtc2UuYWxla2JlcmcubmV0Ci9kbnMtcXVlcnk'
  [static.dnscrypt-pl]
    stamp = 'sdns://AQcAAAAAAAAAFDE3OC4yMTYuMjAxLjEyODoyMDUzIH9hfLgepVPSNMSbwnnHT3tUmAUNHb8RGv7mmWPGR6FpGzIuZG5zY3J5cHQtY2VydC5kbnNjcnlwdC5wbA'
  [static.odoh-jp-tiar-app]
    stamp = 'sdns://BQcAAAAAAAAAC2pwLnRpYXIuYXBwBS9vZG9o'